import logging
from typing import List
from services.llm.base import LLMProvider
from core.exceptions import LLMProviderError

logger = logging.getLogger("nexusmind.llm.router")


class LLMRouter:
    def __init__(self, providers: List[LLMProvider]):
        self.providers = providers

    async def complete(self, system_prompt: str, user_message: str) -> str:
        last_error = None
        for provider in self.providers:
            provider_name = provider.__class__.__name__
            try:
                logger.info(f"Attempting completion via {provider_name}")
                result = await provider.complete(system_prompt, user_message)
                logger.info(f"Completion successfully generated by {provider_name}")
                return result
            except LLMProviderError as e:
                logger.warning(f"Provider {provider_name} failed: {e}. Attempting next provider...")
                last_error = e
            except Exception as e:
                logger.error(f"Unexpected failure in {provider_name}: {e}")
                last_error = e

        raise LLMProviderError(f"All configured LLM providers failed. Last error: {str(last_error)}")
